Various technical fixes and style guide changes in Data Explorer
Public-Health-Scotland/Hospital-Acute-Activity pull request #40
Opened 2022-11-11 10:29 UTC by JFix89

Hi John,

Thanks again for taking a look over this. I've made quite a few changes to the Data Explorer to improve the look of several charts with the new PHS colour palette. I've also made style guide changes to the UI text and dropdown menus and made technical tweaks (e.g. changing the tooltip for the CBF diagram and reordering quarters in the dropdowns so they appear chronologically). Please let me know if you have any questions on any of this - happy to have a call and demo things in the Data Explorer if that would help too.

Thanks,

James

2022-11-11 16:40 UTC, JohnPercivalPHS requested changes
Hi James,

The text changes and updated colour palette look great.

However, we need the html tags class names to match those in the css.

Thanks,

John

2022-11-11 16:40 UTC, JohnPercivalPHS commented on Data-Explorer/ui.R
> -                                class = "special-link"), " and ",
Change back.

2022-11-11 16:40 UTC, JohnPercivalPHS commented on Data-Explorer/ui.R
> -                                class = "special-link"), "sections"),
Change back.

2022-11-11 16:40 UTC, JohnPercivalPHS commented on Data-Explorer/ui.R
> -                      class = "special-link"),
Change back.

2022-11-11 16:40 UTC, JohnPercivalPHS commented on Data-Explorer/ui.R
> +                 class = "special_link"),
change special_link back to special-link

2022-11-11 16:40 UTC, JohnPercivalPHS commented on Data-Explorer/ui.R
> -                 class = "special-link"),
Change back.

2022-11-14 13:22 UTC, JohnPercivalPHS commented on Data-Explorer/global.R
> +    mutate(file = case_when(file %in% "Inpatients/Day Cases" ~ "Inpatients/day cases",
These should be changed in functions.R like the rest of the naming changes.

2022-11-14 13:23 UTC, JohnPercivalPHS requested changes
Hi James,

Please can you move the naming changes to functions.R?

Thanks,

John

2022-11-14 13:48 UTC, JFix89 commented
Hi John,

I've sent a separate email on this a moment ago - agree that it would be better to do as you suggest to make scripts consistent, but can this be put off until after the publication and added to the development tab? I'll gladly pick it up then (along with some other outstanding improvements) but conscious of deadlines for the data explorer at the moment and not keen on tinkering with the code just now when everything is working as it should.

Thanks,

James

2022-11-14 16:06 UTC, JohnPercivalPHS approved these changes
Hi, 

All looks good and thanks for adding the new colour pallette scheme.

John

2022-11-14 16:06 UTC, merged